Bugfix: AttributeError: 'module' object has no attribute '__file__' when you used ``pip install`` instead of ``easy_install``.
That's because namespace packages created by pip have no __file__.

It makes no sense to look at zope.app.__file__ in the modern eggified world
anyway; remove that legacy code and make IZopeVersion utility return
"Meaningless".